### ISSUE TITLE
"lxsu bash" results in frozen shell prompt

### ISSUE THREAD

**Issue by adrelanos** [lxqt/lxqt-sudo#113]
##### Expected Behavior

Functional bash root prompt as usual. (As it was the case with gksudo / `kdesudo bash`.)

##### Current Behavior

```
lxsu bash
lxqt-sudo: Stripping child environment except for: DISPLAY, LANG, LANGUAGE, LC_ADDRESS, LC_ALL, LC_COLLATE, LC_CTYPE, LC_IDENTIFICATION, LC_MEASUREMENT, LC_MESSAGES, LC_MONETARY, LC_NAME, LC_NUMERIC, LC_PAPER, LC_TELEPHONE, LC_TIME, PATH, QT_PLATFORM_PLUGIN, QT_QPA_PLATFORMTHEME, WAYLAND_DISPLAY, XAUTHLOCALHOSTNAME, XAUTHORITY
```
Shell prompt frozen. Cannot type anything. ctrl + c does nothing either.

##### Steps to Reproduce (for bugs)

1. upgrade Debian stretch to Debian buster (in Qubes OS)
2. `sudo apt-get install --no-install-recommends lxqt-sudo`
3. `lxsu bash`

##### Context

I guess starting a bash root prompt is so common that it doesn't need further reasoning?

##### System Information

* Distribution & Version: Debian buster (in Qubes)
* Kernel: `Linux version 4.14.74-1.pvops.qubes.x86_64 (user@build-fedora4) (gcc version 6.4.1 20170727 (Red Hat 6.4.1-1) (GCC)) #1 SMP Mon Oct 8 17:14:24 UTC 2018`
* Qt Version: `libqt5designer5:amd64                         5.11.3-4`
* liblxqt Version: 0.14.1
* lxqt-build-tools Version: was build by Debian
* Package version: 0.14.1-1

**Comment by palinek** [comment]
> I guess starting a bash root prompt is so common that it doesn't need further reasoning?

No. That is completely uncommon, IMO. lxqt-sudo is meant to start elevated GUI application by using a GUI prompt for credentials.

Using it in a terminal to run bash is completely out of scope. In terminal you can use su/sudo directly w/o a need of graphical extension as lxqt-sudo.
