### ISSUE TITLE
lxqt-sudo fails if sudo is not available

### ISSUE THREAD

**Issue by lucasart** [lxqt/lxqt-sudo#150]
##### Expected Behavior
lxqt-sudo should use su if sudo is not available.

##### Current Behavior
fails if sudo is not present.

##### Possible Solution

- Use su by default, because su is ubiquitous (sudo is not).
- Or follow a waterfall logic: if sudo is present, use it, otherwise use su.

##### Steps to Reproduce (for bugs)
**GUI**
Tools -> Open as Root in PCManFM fails (silently).

**CLI**
```
$ lxqt-sudo ls /etc
lxqt-sudo: Stripping child environment except for: DISPLAY,LANG,LANGUAGE,LC_ADDRESS,LC_ALL,LC_COLLATE,LC_CTYPE,LC_IDENTIFICATION,LC_MEASUREMENT,LC_MESSAGES,LC_MONETARY,LC_NAME,LC_NUMERIC,LC_PAPER,LC_TELEPHONE,LC_TIME,PATH,QT_PLATFORM_PLUGIN,QT_QPA_PLATFORMTHEME,TERM,WAYLAND_DISPLAY,XAUTHLOCALHOSTNAME,XAUTHORITY
lxqt-sudo: Failed to exec 'sudo': No such file or directory
```
Works fine with -s (su backend):
```
$ lxqt-sudo -s ls /etc

adjtime                 hostname           man_db.conf      rc_maps.cfg
arch-release            hosts              mdadm.conf       request-key.conf
```
##### Context
Some distro do not install sudo by default. And some power users choose not to use it. LXQt should not force the choice of sudo over su.

`lxqt-sudo -s` works without sudo, but is useless in practice, because GUI programs call lxqt-sudo without the parameter to specify which backend to use.

Example from PCManFM code (settings.cpp):
```
suCommand_ = settings.value(QStringLiteral("SuCommand"), QStringLiteral("lxqt-sudo %s")).toString();
```
Should PCManFM be patched to implement the waterfall ? I don't think so. The root cause of the problem is lxqt-sudo, which, once fixed, will fix it for all GUI programs that use it.

##### System Information
* Distribution & Version: Arch linux
* Kernel: Linux 5.7.5-arch1-1
* Qt Version: Qt version 5.15.0
* liblxqt Version: liblxqt 0.15.1-1
* lxqt-build-tools Version: lxqt-build-tools 0.7.0-1
* Package version: lxqt-sudo 0.15.0-1

**Comment by tsujan** [comment]
> Should PCManFM be patched

Apart from your report, yes, pcmanfm-qt needs a PR: `lxqt-sudo %s` should be replaced by `lxsudo dbus-run-session -- %s` — although the latter is already in the default `settings.conf`, a little more consistency is better. Thanks for the indirect reminder!

**Comment by tsujan** [comment]
And directly related to your report:

Since (1) most distros have `sudo`, (2) we have `lxqt-sudo -s`, (3) we also have `lxsu` and (4) pcmanfm-qt's switch command is configurable, I don't see the relevance of this report.

Please see `man lxqt-sudo`.

**Comment by lucasart** [comment]
What do you suggest the user to do concretely ?

As I showed in the code snippet from pcmanfm-qt, the command is *hardcoded* to lxqt-sudo, and it will not work withoutsudo.

Having lxsu and lxqt-sudo -s doesn't change that.

**Comment by palinek** [comment]
> As I showed in the code snippet from pcmanfm-qt, the command is hardcoded to lxqt-sudo,

No. It's not. You just showed the final fallback value.

**Comment by tsujan** [comment]
> What do you suggest the user to do concretely ?

Being a power user doesn't mean that you shouldn't take a look at pcmanfm-qt → Preferences.

**Comment by lucasart** [comment]
Thanks. I didn't realize you could customize the command in pcmanfm-qt.

But there is still a problem:
```
$ lxsu pcmanfm-qt 

QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
```
which is nonsense, because:
```
$ printenv |grep XDG_RUNTIME
XDG_RUNTIME_DIR=/run/user/1000
```
and even if I login as root, still the same value:
```
$ printenv |grep XDG_RUNTIME
XDG_RUNTIME_DIR=/run/user/1000
```
I checked, the directory `/run/user/1000` is there.

**Comment by tsujan** [comment]
> which is nonsense, because:...

You jumped to a conclusion again ;) No, it isn't nonsense.

**Comment by lucasart** [comment]
Where am I jumping to conclusion ?

I am a *user*. Not an expert of the LXQT codebase. And, for me there is a contradiction between:

**observation 1**
```
$ lxsu pcmanfm-qt 
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
```

**observation 2**
```
$ printenv |grep XDG_RUNTIME
XDG_RUNTIME_DIR=/run/user/1000
```

**Comment by tsujan** [comment]
Compare `printenv` and `lxsu printenv` with each other. Also, if you search `XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'` on Internet, you'll find out that it isn't specific to LXQt or a big deal...

**Comment by lucasart** [comment]
it prevents pvmanfm-qt from starting. So it is a  big deal. If it was only a warning that when using Qt applications as root an unusual temp holder is used, because the usual one could not be found, I would agree that it is somewhat benign.

Or perhaps I am jumping to conclusions again, and that's not what prevents pcmanfm-qt from starting (when called with lxsu). But the only error message I see is this, and the program refuses to start.

**Comment by tsujan** [comment]
> it prevents pvmanfm-qt from starting

It doesn't.

> Or perhaps I am jumping to conclusions again,

Yes.

> and that's not what prevents pcmanfm-qt from starting

Right. pcmanfm-qt and similar apps need `dbus-run-session` to be run as root. The GUI shows that and it's in the default switch command.

>  But the only error message I see is this

It's not an error message but a harmless `qWarning` in Qt's `qstandardpaths_unix.cpp`.

**Comment by lucasart** [comment]
> Right. pcmanfm-qt and similar apps need `dbus-run-session` to be run as root. The GUI shows that and it's in the default switch command.

Thanks. That worked. It was not the default, but I am using the pcmanfm-qt from arch version 0.15.1.

Indeed `lxsu printenv` and `su -c printenv` return completelt different results. I naively thought that the environment was just a function of the user, apparently not...

**Comment by tsujan** [comment]
> Indeed lxsu printenv and su -c printenv return completelt different results.

Years ago, LXQt devs agreed that `lxqt-sudo` should include only certain EVs, mostly for security reasons.

BTW, mere `su` or `sudo` should never be used with GUI apps; otherwise, it might change the permissions of their config files and give the user a real headache. That's why we have `lxqt-sudo`. Maybe, that's also the main "reason" behind the odd decisions about disallowing root instances of GUI apps altogether in some well-known DEs.
