### ISSUE TITLE
lxqt-sudo fails to run applications launched with xdg-su -c '[command] [argument]'

### ISSUE THREAD

**Issue by ghost** [lxqt/lxqt-sudo#189]
An application launched with `xdg-su -c '[command] [argument]'` will not start after approving its execution in the password dialog.

##### Expected Behavior

`xdg-su -c '[command] [argument]'` should translate to: `lxqt-sudo [command] [argument]`

##### Current Behavior

`xdg-su -c '[command] [argument]'` translates to: `lxqt-sudo '[command] [argument]'`

Result: the execution of the program fails because no executable with the name '[command] [argument]' exists.

##### Possible Solution

Remove the quotation marks around the command.

##### Steps to Reproduce

1. In QTerminal run: xdg-su -c 'qterminal -e bash'
2. The command shown in the password dialog is: 'qterminal -e bash' (should be: qterminal -e bash)
3. Enter the superuser password and approve the execution
4. The application fails to run (exec: qterminal -e bash: not found)

##### Context

Administrative YaST modules in openSUSE can be launched directly via their respective .desktop file, where the command
`xdg-su -c '/sbin/yast2 [module]'` is used.

Not being able to start an application this way has the consequence, that you cannot open any of these modules directly from the start menu or via an application launcher.

##### System Information

* Distribution & Version: openSUSE Tumbleweed 20221017
* Kernel: 6.0.1-1-default
* Qt Version: 5.15.6
* liblxqt Version: 1.1.0-2.2
* Package version: 1.1.0-1.4

**Comment by tsujan** [comment]
How can `xdg-su` be related to `lxqt-sudo`? It even doesn't know of `lxqt-sudo`.

**Comment by NDex211** [comment]
Hi, first of all thanks for the reply.

If I launch an app, for example xdg-su -c '/sbin/yast2', the lxqt-sudo password dialog opens. I enter my password and YaST opens.

But if I run xdg-su -c '/sbin/yast2 bootloader', the program does not start afterwards. The password dialog shows me the whole command wrapped in quotation marks and I think, that may be the reason why.

I hope that made things more clear?

Best regards.

**Comment by tsujan** [comment]
@NDex211, I understood your problem. My question was why you thought it was related to `lxqt-sudo`. As far as I know, `xdg-su` is an old program that hasn't been developed for 9 years (→ https://github.com/tarakbumba/xdg-su).

**Comment by NDex211** [comment]
As I understood it, the command I pass to `xdg-su` will be executed via `lxqt-sudo` in the end. That combined with the circumstance that I never encountered this issue in any other desktop environment before, lead me to the conclusion, that this may be a problem with `lxqt-sudo`.

**Comment by NDex211** [comment]
Soo I'm an idiot. I took a look at the `xdg-su` [script](https://gitlab.freedesktop.org/xdg/xdg-utils/-/blob/master/scripts/xdg-su.in) and the call `$LXQTSU -s "$cmd"` in line 87 is why this does not work...

The reason this script is installed in the first place, since `xdg-utils` excludes it by default, is because openSUSE does have a patch in place to add it to the installation.

So yeah, it is a problem with `xdg-su`... I am very sorry for wasting your time and thank you for your patience.
