### ISSUE TITLE
Support for Doas

### ISSUE THREAD

**Issue by Red1922** [lxqt/lxqt-sudo#195]
## Expected Behavior

lxqt-sudo should run using doas without an issue when specified with a hypothetical doas backend flag.

## Current Behavior

lxqt-sudo fails to run without sudo. Symlinking /usr/bin/doas to /usr/bin/sudo produces obvious errors.

## Possible Solution

Adding a doas backend and appropriate flag to enable it on command.

## Steps to Reproduce (for bugs)

1. System without sudo. Doas symlinked to sudo.
2. Open terminal.
3. Run `lxqt-sudo echo "Trial1"`
4. Errors (provided in attached illustration)
[Illustration Hyperlink](https://autumn.revolt.chat/attachments/e4sCoyNNxEJn1HfhsmT4QEKNy195RVtOuBbearqCUb/image.png)

## Context

Unable to use lxqt-sudo on a doas based system. Alternating with pkexec instead for the meantime.

## System Information

* Distribution & Version: Void GNU/Linux GLibC - Latest
* Kernel: Linux 6.1.12_1
* Qt Version: qt5-5.15.7+20221119_1
* liblxqt Version: 1.2.0_1
* lxqt-build-tools Version: 0.12.0_1
* Package version: 1.2.0_1

**Comment by palinek** [comment]
Here you go -> #196

**Comment by Red1922** [comment]
Amazing. Thanks.

**Comment by palinek** [comment]
> Red1922 closed this as completed 

The implementing PR is not merged to master yet. Why did you close this?

**Comment by Red1922** [comment]
I didn't know we had to keep this open until the PR was merged. I have not made many github issues yet. Thanks for correcting.
