### ISSUE TITLE
Native Wayland support

### ISSUE THREAD

**Issue by adrelanos** [lxqt/lxqt-sudo#203]
What are your plans regarding native Wayland support? Under Wayland it is no longer possible to run GUI applications with root rights.

Therefore I hope you are not planning on deprecating `lxqt-sudo`. It could still act as a secure `SUDO_ASKPASS` tool. Created

* https://github.com/lxqt/lxqt-sudo/issues/202

for that.

**Comment by tsujan** [comment]
> Under Wayland it is no longer possible to run GUI applications with root rights.

Right; under a "purely" Wayland-based session (whatever it may mean), it may not be possible. But, months ago, I needed to run `gsmartcontrol_polkit` under Wayfire+LXQt, and this simple script worked:

```sh
#!/bin/bash
xhost +SI:localuser:root
/usr/bin/gsmartcontrol_polkit
xhost -SI:localuser:root
exit
```

**Comment by tsujan** [comment]
> Therefore I hope you are not planning on deprecating lxqt-sudo.

There's no plan.

**Comment by adrelanos** [comment]
> > Under Wayland it is no longer possible to run GUI applications with root rights.
> 
> Right; under a "purely" Wayland-based session (whatever it may mean),

I believe that 's called native Wayland.

> But, months ago, I needed to run `gsmartcontrol_polkit` under Wayfire+LXQt, and this simple script worked:
> 
> ```shell
> #!/bin/bash
> xhost +SI:localuser:root
> /usr/bin/gsmartcontrol_polkit
> xhost -SI:localuser:root
> exit
> ```

Presumably this is using Xwayland (X11 emulation). I.e. not native ("real") Wayland.

Long term Xwayland might be deprecated, bit rot, get less compatible, no longer installed by default or one wanted to go full native Wayland without Xwayland being installed. Therefore it might be a good idea to phase out all the hacks.

**Comment by tsujan** [comment]
> not native ("real") Wayland.

You asked about plans for Wayland. After more than a decade, X11 is still mostly used. No one has a reason to think about deprecation.

What we do in LXQt about Wayland is two-fold: Making apps work on it too, as far as Qt allows; and finding the best Wayland compositor for LXQt — labwc is the winner for now. Deprecation is not planned.

**Comment by tsujan** [comment]
BTW, you could use https://github.com/lxqt/lxqt/discussions for questions.
