### ISSUE TITLE
Preserve more env vars

### ISSUE THREAD

**Issue by sergwish** [lxqt/lxqt-sudo#216]
Any program started with lxqt-sudo does not receive information about current HiDPI scaling settings.
So its interface is not scaled properly.

##### Expected Behavior

Interface scaling settings are applied to all applications.

##### Current Behavior

Interface of any application run with lxqt-sudo is not scaled.

##### Possible Solution

Add "GDK_SCALE", "GDK_DPI_SCALE" and "QT_SCALE_FACTOR" to the list of preserved environment variables ALLOWED_VARS in sudo.cpp (lines 100 - 105). Maybe also add  "GTK_OVERLAY_SCROLLING" and "GTK_CSD".

##### Steps to Reproduce (for bugs)

1. Login as non-root user. Open lxqt-config-session.
2. If global interface scale is set to 1, then set it to 1.5 or more and re-login as the same user
3. Run any GUI app using lxqt-sudo. It's interface is **not scaled**. 
4. Run the same app without lxqt-sudo. See the difference in appearance, which should not exist.

##### Context

It is very inconvenient on 15" 1920x1080 screen to use Managing Software Sources, Synaptic package manager, PCManFM-qt as root, QTerminal as root, FeatherPad as root... Basically any GUI application that requires root privileges to function properly in some situation is barely usable with lxqt-sudo. 

##### System Information

* Distribution & Version: lubuntu 24.04
* Kernel:  6.8.0-35-generic
* Qt Version: 5.15.13
* liblxqt Version: 
* lxqt-build-tools Version: 
* Package version: 1.4.0
* Since:  [commit 07ec9ec](https://github.com/lxqt/lxqt-sudo/commit/07ec9ec14e5d8ff2fe5aba33d9f0a1cd07a4db60) when stripping environment was introduced. #22

**Comment by palinek** [comment]
Sounds reasonable.
@tsujan @luis-pereira @stefonarch What do you think?

**Comment by stefonarch** [comment]
For what my understanding is this should be safe to implement.

**Comment by tsujan** [comment]
I also think this makes perfect sense.

**Comment by tsujan** [comment]
> It is very inconvenient ... to use ... PCManFM-qt as root, QTerminal as root, FeatherPad as root... Basically any GUI application that requires root privileges

IMO, that's absolutely not a good idea, although it's your system and you could anything with it.

However, I agree on preserving more EVs when it's safe.

**Comment by palinek** [comment]
Done in #217
